version: "2"
services:
  redis:
    image: redis:alpine
    container_name: "Redis_Container"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

  app:
    build: ./app
    container_name: "Flask_App_Final"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"